string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(run_dir "${TEST_ROOT}-${run_id}")
file(MAKE_DIRECTORY "${run_dir}")
if(MODE STREQUAL "report")
  if(ASSET_RECORDING)
    file(COPY_FILE "${TEST_EXECUTABLE}" "${run_dir}/asset-test.exe")
    file(WRITE "${run_dir}/mxl-diagnostics.ini" "[Diagnostics]\nenabled=1\nassets=1\n")
    set(TEST_EXECUTABLE "${run_dir}/asset-test.exe")
  endif()
  execute_process(COMMAND "${TEST_EXECUTABLE}" "${run_dir}" ${TEST_ARGUMENTS}
    WORKING_DIRECTORY "${run_dir}" RESULT_VARIABLE result TIMEOUT 50)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Report check failed: ${result}")
  endif()
  return()
endif()
file(COPY_FILE "${TEST_EXECUTABLE}" "${run_dir}/Game.exe")
set(argument --logging-off)
if(MODE STREQUAL "disabled")
  file(COPY_FILE "${DIAGNOSTICS_INI}" "${run_dir}/mxl-diagnostics.ini")
elseif(MODE STREQUAL "enabled")
  file(READ "${DIAGNOSTICS_INI}" settings)
  string(REPLACE "enabled=0" "enabled=1" settings "${settings}")
  file(WRITE "${run_dir}/mxl-diagnostics.ini" "${settings}")
  set(argument --logging-on)
endif()
execute_process(COMMAND "${run_dir}/Game.exe" "${run_dir}/unused" ${argument}
  WORKING_DIRECTORY "${run_dir}" RESULT_VARIABLE result TIMEOUT 20)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Logging ${MODE} check failed: ${result}")
endif()
