add_executable(dx12_reveal_probe_test tests/reveal_probe_test.cpp src/dx12/reveal_probe.cpp)
target_include_directories(dx12_reveal_probe_test PRIVATE d2gl/d2gl/vendor/include)
target_compile_definitions(dx12_reveal_probe_test PRIVATE MXL_REVEAL_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_reveal_probe_test PRIVATE mxl_diagnostics)
add_executable(dx12_input_profile_test tests/input_profile_test.cpp)
add_executable(dx12_auto_reveal_test tests/auto_reveal_test.cpp)
target_link_libraries(dx12_auto_reveal_test PRIVATE mxl_diagnostics)
target_compile_definitions(dx12_auto_reveal_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_input_profile_test PRIVATE mxl_diagnostics)
target_compile_definitions(dx12_input_profile_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_executable(dx12_shader_test tests/shader_test.cpp)
target_link_libraries(dx12_shader_test PRIVATE mxl_dx12_shader)
add_executable(dx12_timing_test d2gl/d2gl/src/mxl_smoothing.c)
target_compile_definitions(dx12_timing_test PRIVATE MXL_SMOOTHING_TEST _CRT_SECURE_NO_WARNINGS)
target_link_libraries(dx12_timing_test PRIVATE advapi32)
add_executable(dx12_preset_test tests/preset_test.cpp)
target_link_libraries(dx12_preset_test PRIVATE mxl_dx12_shader)
target_compile_definitions(dx12_shader_test PRIVATE MXL_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
add_executable(dx12_diagnostics_test tests/diagnostics_test.cpp)
target_link_libraries(dx12_diagnostics_test PRIVATE mxl_dx12_device dsound)
target_compile_definitions(dx12_diagnostics_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_executable(dx12_device_test tests/device_test.cpp)
target_link_libraries(dx12_device_test PRIVATE mxl_dx12_device)
add_executable(dx12_render_test tests/render_test.cpp)
target_link_libraries(dx12_render_test PRIVATE mxl_dx12_backend)
add_executable(dx12_upload_cache_test tests/upload_cache_test.cpp)
target_link_libraries(dx12_upload_cache_test PRIVATE mxl_dx12_backend)
add_executable(dx12_glide_test tests/glide_test.cpp)
target_link_libraries(dx12_glide_test PRIVATE mxl_dx12_backend)
target_compile_definitions(dx12_glide_test PRIVATE MXL_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/external/blast/blast.c")
  add_executable(dx12_mpq_blast tests/blast_cli.c external/blast/blast.c)
  target_include_directories(dx12_mpq_blast PRIVATE external/blast)
endif()

add_executable(dx12_menu_test tests/menu_test.cpp src/dx12/fps_menu.cpp
  "${MXL_IMGUI_DIR}/imgui.cpp" "${MXL_IMGUI_DIR}/imgui_draw.cpp"
  "${MXL_IMGUI_DIR}/imgui_widgets.cpp" "${MXL_IMGUI_DIR}/imgui_tables.cpp" "${MXL_IMGUI_DIR}/imgui_impl_dx12.cpp")
target_include_directories(dx12_menu_test PRIVATE src/dx12 d2gl/d2gl/vendor/include)
target_compile_definitions(dx12_menu_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS MXL_BUILD_DIR="${CMAKE_BINARY_DIR}")
target_link_libraries(dx12_menu_test PRIVATE mxl_dx12_device d3dcompiler)

set(mxl_plain_tests dx12_shader_test dx12_timing_test dx12_device_test dx12_render_test dx12_glide_test dx12_menu_test)
foreach(test IN LISTS mxl_plain_tests)
  add_test(NAME ${test} COMMAND $<TARGET_FILE:${test}>)
  set_tests_properties(${test} PROPERTIES TIMEOUT 60)
endforeach()
set(mxl_log_tests dx12_diagnostics_test dx12_upload_cache_test dx12_input_profile_test dx12_reveal_probe_test dx12_auto_reveal_test)
foreach(test IN LISTS mxl_log_tests)
  add_test(NAME ${test} COMMAND ${CMAKE_COMMAND}
    "-DTEST_EXECUTABLE=$<TARGET_FILE:${test}>"
    "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/${test}"
    "-DMODE=report" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
  set_tests_properties(${test} PROPERTIES TIMEOUT 60)
endforeach()
foreach(mode missing disabled enabled)
  add_test(NAME logging_${mode} COMMAND ${CMAKE_COMMAND}
    "-DTEST_EXECUTABLE=$<TARGET_FILE:dx12_auto_reveal_test>"
    "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/logging-${mode}"
    "-DDIAGNOSTICS_INI=${CMAKE_CURRENT_SOURCE_DIR}/mxl-diagnostics.ini"
    "-DMODE=${mode}" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
  set_tests_properties(logging_${mode} PROPERTIES TIMEOUT 30)
endforeach()
