add_executable(dx12_reveal_probe_test tests/reveal_probe_test.cpp src/dx12/reveal_probe.cpp)
target_include_directories(dx12_reveal_probe_test PRIVATE d2gl/d2gl/vendor/include)
target_compile_definitions(dx12_reveal_probe_test PRIVATE MXL_REVEAL_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_reveal_probe_test PRIVATE mxl_diagnostics)
add_executable(dx12_input_profile_test tests/input_profile_test.cpp)
add_executable(native_loot_test tests/native_loot_test.cpp)
add_executable(native_loot_pickup_test tests/native_loot_pickup_test.cpp)
add_executable(native_loot_selection_test tests/native_loot_selection_test.cpp)
target_include_directories(native_loot_selection_test PRIVATE src/dx12 d2gl/d2gl/src d2gl/d2gl/vendor/include)
target_compile_definitions(native_loot_selection_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(native_loot_selection_test PRIVATE mxl_diagnostics)
add_test(NAME native_loot_selection_test COMMAND $<TARGET_FILE:native_loot_selection_test>)
set_tests_properties(native_loot_selection_test PROPERTIES TIMEOUT 30)
target_include_directories(native_loot_pickup_test PRIVATE src/dx12)
target_compile_definitions(native_loot_pickup_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_test(NAME native_loot_pickup_test COMMAND $<TARGET_FILE:native_loot_pickup_test>)
add_executable(native_loot_labels_test tests/native_loot_labels_test.cpp)
target_include_directories(native_loot_labels_test PRIVATE src/dx12)
target_compile_definitions(native_loot_labels_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_test(NAME native_loot_labels_test COMMAND $<TARGET_FILE:native_loot_labels_test>)
add_executable(world_objects_test tests/world_objects_test.cpp)
target_include_directories(world_objects_test PRIVATE src/dx12)
add_test(NAME world_objects_test COMMAND $<TARGET_FILE:world_objects_test>)
set_tests_properties(native_loot_labels_test PROPERTIES TIMEOUT 30)
target_include_directories(native_loot_test PRIVATE src/dx12 d2gl/d2gl/src d2gl/d2gl/vendor/include)
target_compile_options(native_loot_test PRIVATE /fp:precise /arch:SSE2)
target_compile_definitions(native_loot_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_test(NAME native_loot_test COMMAND $<TARGET_FILE:native_loot_test>)
set_tests_properties(native_loot_test PROPERTIES TIMEOUT 30)
add_executable(dx12_tile_cache_test tests/tile_cache_test.cpp)
add_executable(dx12_archive_hash_cache_test tests/archive_hash_cache_test.cpp src/dx12/archive_hash_cache.cpp)
target_include_directories(dx12_archive_hash_cache_test PRIVATE src/dx12 d2gl/d2gl/vendor/include)
target_compile_definitions(dx12_archive_hash_cache_test PRIVATE MXL_ARCHIVE_HASH_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_archive_hash_cache_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/d2gl/d2gl/vendor/lib/detours.lib")
add_test(NAME dx12_archive_hash_cache_test COMMAND $<TARGET_FILE:dx12_archive_hash_cache_test>)
set_tests_properties(dx12_archive_hash_cache_test PROPERTIES TIMEOUT 60)
target_link_libraries(dx12_tile_cache_test PRIVATE mxl_diagnostics)
target_compile_definitions(dx12_tile_cache_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_test(NAME dx12_tile_cache_test COMMAND $<TARGET_FILE:dx12_tile_cache_test>)
set_tests_properties(dx12_tile_cache_test PROPERTIES TIMEOUT 60)
add_executable(dx12_sound_probe_test tests/sound_probe_test.cpp src/dx12/sound_probe.cpp)
target_compile_definitions(dx12_sound_probe_test PRIVATE MXL_SOUND_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_sound_probe_test PRIVATE mxl_diagnostics)
add_executable(dx12_sound_cancel_test tests/sound_cancel_test.cpp src/dx12/sound_cancel.cpp)
target_compile_definitions(dx12_sound_cancel_test PRIVATE MXL_SOUND_CANCEL_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_sound_cancel_test PRIVATE mxl_diagnostics)
add_test(NAME dx12_sound_cancel_test COMMAND $<TARGET_FILE:dx12_sound_cancel_test>)
set_tests_properties(dx12_sound_cancel_test PROPERTIES TIMEOUT 30)
add_executable(dx12_asset_probe_test tests/asset_probe_test.cpp src/dx12/asset_probe.cpp)
target_compile_definitions(dx12_asset_probe_test PRIVATE MXL_ASSET_TEST WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_asset_probe_test PRIVATE mxl_diagnostics)
add_executable(dx12_auto_reveal_test tests/auto_reveal_test.cpp)
target_link_libraries(dx12_auto_reveal_test PRIVATE mxl_diagnostics)
target_compile_definitions(dx12_auto_reveal_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(dx12_input_profile_test PRIVATE mxl_diagnostics)
target_compile_definitions(dx12_input_profile_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_executable(dx12_shader_test tests/shader_test.cpp)
target_link_libraries(dx12_shader_test PRIVATE mxl_dx12_shader)
add_executable(dx12_timing_test d2gl/d2gl/src/mxl_smoothing.c)
add_executable(visual_clock_test tests/visual_clock_test.c)
target_include_directories(visual_clock_test PRIVATE d2gl/d2gl/src)
target_compile_definitions(visual_clock_test PRIVATE _CRT_SECURE_NO_WARNINGS)
add_test(NAME visual_clock_test COMMAND $<TARGET_FILE:visual_clock_test>)
add_executable(render_clock_test tests/render_clock_test.c)
target_include_directories(render_clock_test PRIVATE d2gl/d2gl/src)
target_compile_definitions(render_clock_test PRIVATE _CRT_SECURE_NO_WARNINGS)
add_test(NAME render_clock_test COMMAND $<TARGET_FILE:render_clock_test>)
target_compile_definitions(dx12_timing_test PRIVATE MXL_SMOOTHING_TEST _CRT_SECURE_NO_WARNINGS)
target_link_libraries(dx12_timing_test PRIVATE advapi32)
add_executable(dx12_preset_test tests/preset_test.cpp)
target_link_libraries(dx12_preset_test PRIVATE mxl_dx12_shader)
target_compile_definitions(dx12_shader_test PRIVATE MXL_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
add_executable(dx12_diagnostics_test tests/diagnostics_test.cpp)
target_link_libraries(dx12_diagnostics_test PRIVATE mxl_dx12_device dsound)
target_compile_definitions(dx12_diagnostics_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_executable(dx12_device_test tests/device_test.cpp)
target_link_libraries(dx12_device_test PRIVATE mxl_dx12_device)
add_executable(dx12_render_test tests/render_test.cpp)
target_link_libraries(dx12_render_test PRIVATE mxl_dx12_backend)
add_executable(dx12_upload_cache_test tests/upload_cache_test.cpp)
target_link_libraries(dx12_upload_cache_test PRIVATE mxl_dx12_backend)
add_executable(dx12_glide_test tests/glide_test.cpp)
add_executable(glide_texture_cache_test tests/glide_texture_cache_test.cpp d2gl/glide3x/src/glide/texture_manager.cpp)
target_include_directories(glide_texture_cache_test PRIVATE src/dx12 d2gl/glide3x/src d2gl/d2gl/vendor/include)
add_test(NAME glide_texture_cache_test COMMAND $<TARGET_FILE:glide_texture_cache_test>)
add_executable(loot_cache_workload_test tests/loot_cache_workload_test.cpp d2gl/glide3x/src/glide/texture_manager.cpp)
target_include_directories(loot_cache_workload_test PRIVATE d2gl/glide3x/src d2gl/d2gl/vendor/include)
add_test(NAME loot_cache_workload_test COMMAND $<TARGET_FILE:loot_cache_workload_test>)
set_tests_properties(loot_cache_workload_test PROPERTIES TIMEOUT 30)
add_executable(native_loot_overlap_test tests/native_loot_overlap_test.cpp)
add_executable(native_loot_driver_test tests/native_loot_driver_test.cpp d2gl/glide3x/src/glide/texture_manager.cpp)
target_include_directories(native_loot_driver_test PRIVATE src/dx12 d2gl/d2gl/src d2gl/glide3x/src d2gl/d2gl/vendor/include)
target_compile_definitions(native_loot_driver_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
target_compile_options(native_loot_driver_test PRIVATE /fp:precise)
set(MXL_NATIVE_GAME_DIR "" CACHE PATH "Optional installed 1.13c game directory for offline native driver verification")
add_executable(render_native_test tests/render_native_test.c)
target_compile_definitions(render_native_test PRIVATE _CRT_SECURE_NO_WARNINGS)
target_link_libraries(render_native_test PRIVATE advapi32)
if(EXISTS "${MXL_NATIVE_GAME_DIR}/d2fps.dll")
  add_test(NAME render_native_test COMMAND $<TARGET_FILE:render_native_test> "${MXL_NATIVE_GAME_DIR}/d2fps.dll")
  set_tests_properties(render_native_test PROPERTIES TIMEOUT 30)
endif()
if(EXISTS "${MXL_NATIVE_GAME_DIR}/D2Glide.dll" AND EXISTS "${MXL_NATIVE_GAME_DIR}/D2CMP.dll")
  add_test(NAME native_loot_driver_test COMMAND $<TARGET_FILE:native_loot_driver_test> "${MXL_NATIVE_GAME_DIR}")
  set_tests_properties(native_loot_driver_test PROPERTIES TIMEOUT 180)
endif()
target_link_libraries(native_loot_overlap_test PRIVATE mxl_dx12_backend)
target_compile_definitions(native_loot_overlap_test PRIVATE MXL_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_options(native_loot_overlap_test PRIVATE /fp:precise)
add_test(NAME native_loot_overlap_test COMMAND $<TARGET_FILE:native_loot_overlap_test>)
set_tests_properties(native_loot_overlap_test PROPERTIES TIMEOUT 60)
target_link_libraries(dx12_glide_test PRIVATE mxl_dx12_backend)
target_compile_definitions(dx12_glide_test PRIVATE MXL_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/external/blast/blast.c")
  add_executable(dx12_mpq_blast tests/blast_cli.c external/blast/blast.c)
  target_include_directories(dx12_mpq_blast PRIVATE external/blast)
endif()

add_executable(dx12_menu_test tests/menu_test.cpp src/dx12/fps_menu.cpp
  "${MXL_IMGUI_DIR}/imgui.cpp" "${MXL_IMGUI_DIR}/imgui_draw.cpp"
  "${MXL_IMGUI_DIR}/imgui_widgets.cpp" "${MXL_IMGUI_DIR}/imgui_tables.cpp" "${MXL_IMGUI_DIR}/imgui_impl_dx12.cpp")
target_include_directories(dx12_menu_test PRIVATE src/dx12 d2gl/d2gl/vendor/include)
target_compile_definitions(dx12_menu_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS MXL_BUILD_DIR="${CMAKE_BINARY_DIR}")
target_link_libraries(dx12_menu_test PRIVATE mxl_dx12_device d3dcompiler)

set(mxl_plain_tests dx12_shader_test dx12_timing_test dx12_device_test dx12_render_test dx12_glide_test dx12_menu_test)
foreach(test IN LISTS mxl_plain_tests)
  add_test(NAME ${test} COMMAND $<TARGET_FILE:${test}>)
  set_tests_properties(${test} PROPERTIES TIMEOUT 60)
endforeach()
add_test(NAME reveal_preselection_without_logging COMMAND $<TARGET_FILE:dx12_reveal_probe_test>
  "${CMAKE_BINARY_DIR}/test-output/preselection-only" --preselection-only)
set_tests_properties(reveal_preselection_without_logging PROPERTIES TIMEOUT 30)
if(MXL_ENABLE_DIAGNOSTICS)
add_executable(loot_diagnostics_test tests/loot_diagnostics_test.cpp)
target_link_libraries(loot_diagnostics_test PRIVATE mxl_dx12_device)
target_compile_definitions(loot_diagnostics_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
add_test(NAME loot_diagnostics_auto_start COMMAND ${CMAKE_COMMAND}
  "-DTEST_EXECUTABLE=$<TARGET_FILE:loot_diagnostics_test>"
  "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/loot-auto"
  -DMODE=loot-auto -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
set_tests_properties(loot_diagnostics_auto_start PROPERTIES TIMEOUT 30)
add_test(NAME reveal_before_scene_unsupported COMMAND ${CMAKE_COMMAND}
  "-DTEST_EXECUTABLE=$<TARGET_FILE:dx12_auto_reveal_test>"
  "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/before-scene-unsupported"
  "-DTEST_ARGUMENTS=--before-scene-unsupported"
  "-DMODE=report" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
set_tests_properties(reveal_before_scene_unsupported PROPERTIES TIMEOUT 60)
set(mxl_log_tests dx12_diagnostics_test dx12_upload_cache_test dx12_input_profile_test dx12_reveal_probe_test dx12_auto_reveal_test dx12_asset_probe_test dx12_sound_probe_test)
foreach(test IN LISTS mxl_log_tests)
  set(extra_flags)
  if(test STREQUAL "dx12_asset_probe_test")
    list(APPEND extra_flags "-DASSET_RECORDING=ON")
  endif()
  add_test(NAME ${test} COMMAND ${CMAKE_COMMAND}
    "-DTEST_EXECUTABLE=$<TARGET_FILE:${test}>"
    "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/${test}"
    "-DMODE=report" ${extra_flags} -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
  set_tests_properties(${test} PROPERTIES TIMEOUT 60)
endforeach()
foreach(mode missing disabled enabled)
  add_test(NAME logging_${mode} COMMAND ${CMAKE_COMMAND}
    "-DTEST_EXECUTABLE=$<TARGET_FILE:dx12_auto_reveal_test>"
    "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/logging-${mode}"
    "-DDIAGNOSTICS_INI=${CMAKE_CURRENT_SOURCE_DIR}/mxl-diagnostics.ini"
    "-DMODE=${mode}" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
  set_tests_properties(logging_${mode} PROPERTIES TIMEOUT 30)
endforeach()
else()
  add_executable(public_build_test tests/public_build_test.cpp)
  target_link_libraries(public_build_test PRIVATE mxl_diagnostics)
  target_compile_definitions(public_build_test PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
  add_test(NAME public_build_test COMMAND ${CMAKE_COMMAND}
    "-DTEST_EXECUTABLE=$<TARGET_FILE:public_build_test>"
    "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/public-build"
    -DMODE=public -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
  set_tests_properties(public_build_test PROPERTIES TIMEOUT 30)
  foreach(mode missing disabled)
    add_test(NAME public_reveal_${mode} COMMAND ${CMAKE_COMMAND}
      "-DTEST_EXECUTABLE=$<TARGET_FILE:dx12_auto_reveal_test>"
      "-DTEST_ROOT=${CMAKE_BINARY_DIR}/test-output/public-reveal-${mode}"
      "-DDIAGNOSTICS_INI=${CMAKE_CURRENT_SOURCE_DIR}/mxl-diagnostics.ini"
      "-DMODE=${mode}" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTest.cmake")
    set_tests_properties(public_reveal_${mode} PROPERTIES TIMEOUT 30)
  endforeach()
endif()
